# LightGBM training config

params:
  objective: regression
  metric: rmse
  learning_rate: 0.05
  num_leaves: 31
  device: gpu     # ðŸ”¥ USE GPU if installed

num_boost_round: 1000
early_stopping: 50
seed: 42
